AllCops:
  Exclude:
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"
    - "db/schema.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/*_spec.rb"
